### ISSUE TITLE
Family names containing whitespace should be quoted

### ISSUE THREAD

**Issue by ivan-borisov** [tmcw/systemfontstack#11]
This is not error, but just remove this warning in w3 css validator

> Family names containing whitespace should be quoted. If quoting is omitted, any whitespace characters before and after the name are ignored and any sequence of whitespace characters inside the name is converted to a single space. 

Must be like this
`-apple-system, BlinkMacSystemFont, 'avenir next', avenir, 'helvetica neue', helvetica, Ubuntu,                                  roboto, noto, 'segoe ui', arial, sans-serif;`

**Comment by tmcw** [comment]
Thanks for the suggestion! I'd rather keep this as-is: The w3 validators, for both html and css, are pretty eager with their warnings, even when the input is fully spec-compliant. I'd rather not try to appease them and instead write to the specs.
