### ISSUE TITLE
Chrome on Windows 10 uses Arial, even when Segoe UI is available

### ISSUE THREAD

**Issue by pradyunsg** [tmcw/systemfontstack#12]
Not sure why, but that happens when using the recommendation given here as-is. Even adding quotes and fixing capitalisation doesn't help.

:(

**Comment by victorpoughon** [comment]
Same here. I think it's because Helvetica is in the list before it. Remove Helvetica and Segoe UI is picked.

**Comment by wormeyman** [comment]
`-apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"`

**Comment by anaisbetts** [comment]
This is not fixed on Windows 11 on Edge Dev 103.0.1264.2, fonts continue to render as Arial:

![image](https://user-images.githubusercontent.com/1396/170843794-894ff78d-45ef-4ff1-9ec8-6f3d2ead87cf.png)

```
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.0 Safari/537.36 Edg/103.0.1264.2'
```

**Comment by anaisbetts** [comment]
Indeed, as others have mentioned, removing Helvetica fixes this. I suspect that Chromium is perhaps aliasing Helvetica to Arial for compatibility purposes

**Edit**: Sure enough: https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/platform/fonts/alternate_font_family.h;l=92?q=kHelvetica&ss=chromium

**Comment by tmcw** [comment]
The current rule is:

```
font-family: -apple-system, BlinkMacSystemFont, avenir next, avenir, segoe ui, helvetica neue, helvetica, Ubuntu, roboto, noto, arial, sans-serif;
```

If Windows/Edge is rendering Arial, that'd imply that segoe ui is not available, right? Or is there something I'm missing - as far as I can tell, this font stack is explicitly prioritizing segoe ui over helvetica.

**Comment by anaisbetts** [comment]
Ah, I was going by the site itself, which has the opposite priority, Helvetica > Segoe

```
-apple-system,BlinkMacSystemFont,avenir next,avenir,helvetica neue,helvetica,ubuntu,roboto,noto,segoe ui,arial,sans-serif
```
