### ISSUE TITLE
Connection to sanitize.css typography?

### ISSUE THREAD

**Issue by DougInAMug** [tmcw/systemfontstack#21]
I just noticed that Sanitize also have a font-stack: https://github.com/csstools/sanitize.css#typography

Has anyone been in contact with them? Can we arrive at a common stack?

**Comment by tmcw** [comment]
systemfontstack is really here to spread the good word about system font stacks, whereas sanitize is a library/framework/jumping-off point. i've tried to absorb lessons from the other font stacks and give some good examples, as I assume other projects are doing.
